{"name":   [
    "пуратино",
    "MC ROBOT - Русь встала с колен, так резко что пиздец",
    "MC Скрепецкий - Зольдаты суки Наты",
    "Д Робот - Бомжи апокалипсиса",
    "Д Робот - Лебеда, лебеда, вот вот Америке пизд@ (частушки)",
    "Д Робот MC ROBOT - Боже вождя храни",
    "Д робот - панк частушки 2. опа, опa",
    "МС Д Робот - А ну ка бабка",
    "МС Д Робот - Бузотёр ты меня называла",
    "МС Д Робот - Марш путриотов",
    "МС Д Робот - Пугабе услышит, Пугабе придёт",
    "МС Д Робот - Россия под подошвой",
    "МС Д Робот - Человечный Человек",
    "Песня Семёныча россия 2028 - Песня Семёныча, россия 2028",
    "Семён Скрепецкий - Беспилотник",
    "Семён Скрепецкий - В рай ( Ихтамнет)",
    "Семён Скрепецкий - За подмогой",
    "Семён Скрепецкий - Когда я на почте дроном служил",
    "Семён Скрепецкий - Наши сракеты (АХС)",
    "Семён Скрепецкий - Ненавижу я начальство",
    "Семён Скрепецкий - Сказка об отважном ихтамнете Степане 2 версия.Панк опера",
    "Семён Скрепецкий - Сказочный президент",
    "Скрепецкий - Наша Росгвардия всех сильней",
    "д робот - Smels Like Teen Spirit русский перевод - а убьём ка мы Семёна",
    "д робот - Ихтамнет",
    "д робот - боже покарай пендосов",
    "д робот - деды воевали, можем повторить (1)",
    "д робот - деды воевали, можем повторить",
    "д робот - мне кажется брат нас опять наебали",
    "д робот - путин и пустота",
    "д робот - скромность украшает мужчину",
    "д робот MC Oxxxyroboton - деревня под подошвой.mp3",
    "д робот MC ROBOT - Городской хипстер",
    "дядя робот - мамкин выживальщик. ускоренная",
    "дядя робот - песня про рыбу,муху и бабу",
    "дядя робот - саморазвитие - корчи умное ебало"
    ], 

 "uri" : [
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/a.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/MC ROBOT - Русь встала с колен, так резко что пиздец.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/MC Скрепецкий - Зольдаты суки Наты.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Д Робот - Бомжи апокалипсиса.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Д Робот - Лебеда, лебеда, вот вот Америке пизд@ (частушки).mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Д Робот MC ROBOT - Боже вождя храни.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Д робот - панк частушки 2. опа, опа.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/МС Д Робот - А ну ка бабка.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/МС Д Робот - Бузотёр ты меня называла.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/МС Д Робот - Марш путриотов.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/МС Д Робот - Пугабе услышит, Пугабе придёт .mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/МС Д Робот - Россия под подошвой.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/МС Д Робот - Человечный Человек.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Песня Семёныча россия 2028 - Песня Семёныча, россия 2028.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - Беспилотник.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - В рай ( Ихтамнет).mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - За подмогой. .mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - Когда я на почте дроном служил.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - Наши сракеты (АХС).mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - Ненавижу я начальство.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - Сказка об отважном ихтамнете Степане 2 версия.Панк опера.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Семён Скрепецкий - Сказочный президент .mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/Скрепецкий - Наша Росгвардия всех сильней.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - Smels Like Teen Spirit русский перевод - а убьём ка мы Семёна.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - Ихтамнет.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - боже покарай пендосов.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - деды воевали, можем повторить (1).mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - деды воевали, можем повторить.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - мне кажется брат нас опять наебали.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - путин и пустота.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот - скромность украшает мужчину.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот MC Oxxxyroboton - деревня под подошвой.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/д робот MC ROBOT - Городской хипстер.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/дядя робот - мамкин выживальщик. ускоренная.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/дядя робот - песня про рыбу,муху и бабу.mp3",
     "https://diseno-desarrollo-web-app-cantabria.github.io/alarm/m/дядя робот - саморазвитие - корчи умное ебало.mp3"
 ]  
