{"name":   [
    "Cadena Dial",
    "Los 40 Principales",
    "Los 40 Classic",
    "Cadena Cien",
    "Rock Fm",
    "Loca Fm",
     "RAC 1",
     "Ondacero",
     "Ibiza",
     "RNE",
     "Intereconomia",
     "Cadena Ser",
     "Ibiza Sonica",
     "Vinilo",
     "Cadena Cope",
     "Maxima",
     "Hit",
     "Kiss Fm",
     "Gay Radio",
     "Fresca Radio",
     "Holiday Gim",
     "Radiole",
     "Loca Latino"
     ], 

 "uri" : [
        "https://17873.live.streamtheworld.com/CADENADIAL_SC",
        "http://19983.live.streamtheworld.com/LOS40_SC",
        "https://20863.live.streamtheworld.com/LOS40_CLASSIC_SC",
        "http://flucast-b05-01.flumotion.com/cope/cadena100.mp3", 
        "http://flucast-b01-04.flumotion.com/cope/rockfm-low.mp3",
        "http://audio-online.net:2300/live",
        "https://streaming.rac1.cat/",
        "https://icecast-streaming.nice264.com/ondacero",
        "http://ibizaglobalradio.streaming-pro.com:8024/stream/1/",
        "http://rne.rtveradio.cires21.com/rne.mp3",
        "http://212.85.46.144/siliconorg",
        "https://19983.live.streamtheworld.com/CADENASER_SC",
        "http://s1.sonicabroadcast.com:7005/stream/1/",
        "http://server9.emitironline.com:10923/;",
        "http://flucast-b05-01.flumotion.com/cope/net1.mp3",
        "https://20073.live.streamtheworld.com/MAXIMAFM_SC",
        "https://hitfm.kissfmradio.cires21.com/hitfm.mp3",
        "http://kissfm.kissfmradio.cires21.com/kissfm.mp3",
        "http://icepool.silvacast.com/GAYFM.mp3",
        "http://stream.produccionesdale.com:8899/altacalidad",
        "http://holidaygym.emitironline.com/",
        "http://20723.live.streamtheworld.com/RADIOLE.mp3",
        "http://audio-online.net:8012/live"
     
     ]         
                                          }
